sudo: required

services:
  - docker

language: php

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: VERSION=7.2
    - php: 7.1
      env: VERSION=7.1
    - php: 7.0
      env: VERSION=7.0

before_script:
  - echo "memory_limit=1024M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer install
  - mkdir -p build/logs

script:
  - if [[ $VERSION > 7.0 ]]; then phpdbg -qrr vendor/bin/phpunit --configuration phpunit.xml --coverage-clover=coverage.clover;
    else vendor/bin/phpunit --configuration phpunit.xml; fi

after_script:
  - if [[ $VERSION = 7.2 ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ $VERSION = 7.2 ]]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi
