sudo: required

services:
  - docker

language: php

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: VERSION=latest
    - php: 7.0
      env: VERSION=7.0

before_script:
  - echo "memory_limit=1024M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer install
  - mkdir -p build/logs

script:
  - if [[ $VERSION = 'latest' ]]; then phpdbg -qrr vendor/bin/phpunit --configuration phpunit.xml --coverage-clover=coverage.clover; fi
  - if [[ $VERSION != 'latest' ]]; then vendor/bin/phpunit --configuration phpunit.xml; fi

after_script:
  - if [[ $VERSION = 'latest' ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ $VERSION = 'latest' ]]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi
